pub mod config;
pub mod error;
pub mod server;
pub mod router;
pub mod http;
pub mod cgi;
pub mod upload;
pub mod prelude;
pub mod handlers;
use crate::cgi::*;
use crate::upload::*;
use crate::handlers::*;